name = "dev3-sopadeletras-web"
account_id = "79b48e78b9db791957b966c527f8039a"
compatibility_date = "2026-04-25"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "dev3.sopadeletras.art", custom_domain = true }
]
